<a href="https://colab.research.google.com/github/239-blip/mssp607/blob/main/Assignments/assignment1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

read

In [1]:
!git clone https://github.com/239-blip/mssp607
%cd mssp607
import pandas as pd
ap=pd.read_excel("data/data_academic_performance.xlsx",sheet_name="SABER11_SABERPRO")

Cloning into 'mssp607'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 94 (delta 33), reused 5 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (94/94), 3.16 MiB | 6.31 MiB/s, done.
Resolving deltas: 100% (33/33), done.
/content/mssp607

In [2]:
#quality check
quality_summary = pd.DataFrame({
    "dtype": ap.dtypes.astype(str),
    "missing": ap.isna().sum(),
    "missing_pct": ap.isna().mean().mul(100).round(2),
    "unique_values": ap.nunique()
})
quality_summary

                    dtype  missing  missing_pct  unique_values
COD_S11            object        0          0.0          12411
GENDER             object        0          0.0              2
EDU_FATHER         object        0          0.0             12
EDU_MOTHER         object        0          0.0             12
OCC_FATHER         object        0          0.0             12
OCC_MOTHER         object        0          0.0             12
STRATUM            object        0          0.0              7
SISBEN             object        0          0.0              6
PEOPLE_HOUSE       object        0          0.0             13
Unnamed: 9        float64    12411        100.0              0
INTERNET           object        0          0.0              2
TV                 object        0          0.0              2
COMPUTER           object        0          0.0              2
WASHING_MCH        object        0          0.0              2
MIC_OVEN           object        0          0.0              2
CAR                object        0          0.0              2
DVD                object        0          0.0              2
FRESH              object        0          0.0              2
PHONE              object        0          0.0              2
MOBILE             object        0          0.0              2
REVENUE            object        0          0.0              8
JOB                object        0          0.0              4
SCHOOL_NAME        object        0          0.0           3735
SCHOOL_NAT         object        0          0.0              2
SCHOOL_TYPE        object        0          0.0              4
MAT_S11             int64        0          0.0             69
CR_S11              int64        0          0.0             71
CC_S11              int64        0          0.0             68
BIO_S11             int64        0          0.0             72
ENG_S11             int64        0          0.0             63
Cod_SPro           object        0          0.0          12395
UNIVERSITY         object        0          0.0            134
ACADEMIC_PROGRAM   object        0          0.0             21
QR_PRO              int64        0          0.0            100
CR_PRO              int64        0          0.0            100
CC_PRO              int64        0          0.0            100
ENG_PRO             int64        0          0.0            100
WC_PRO              int64        0          0.0            101
FEP_PRO             int64        0          0.0            236
G_SC                int64        0          0.0            166
PERCENTILE          int64        0          0.0            100
2ND_DECILE          int64        0          0.0              5
QUARTILE            int64        0          0.0              4
SEL                 int64        0          0.0              4
SEL_IHE             int64        0          0.0              4

Does parental education influence outcomes, and if so, how much?

In [3]:
display(ap['EDU_FATHER'].unique())
display(ap['EDU_MOTHER'].unique())

array(['Incomplete Professional Education', 'Complete Secundary',
       'Not sure', 'Complete professional education',
       'Incomplete Secundary', 'Incomplete technical or technological',
       'Complete technique or technology', 'Incomplete primary ',
       'Complete primary ', 'Postgraduate education', 0, 'Ninguno'],
      dtype=object)

array(['Complete technique or technology',
       'Complete professional education', 'Not sure',
       'Complete Secundary', 'Incomplete technical or technological',
       'Incomplete primary ', 'Incomplete Secundary',
       'Incomplete Professional Education', 'Postgraduate education',
       'Complete primary ', 0, 'Ninguno'], dtype=object)

In [4]:
#clean up
df1=ap[~ap['EDU_FATHER'].isin([0,'0','Not sure']) & ~ap['EDU_MOTHER'].isin([0,'0','Not sure'])].copy()
df1['EDU_FATHER']=df1['EDU_FATHER'].str.strip()
df1['EDU_MOTHER']=df1['EDU_MOTHER'].str.strip()

In [5]:
#give catagories values, bed=basic edu, the=tech higher edu, phe=professional higher edu
bed_map={
    "Ninguno": 0,
    "Incomplete primary": 1,
    "Complete primary": 2,
    "Incomplete Secundary": 3,
    "Complete Secundary": 4,
    "Incomplete technical or technological": 4,
    "Complete technique or technology": 4,
    "Incomplete Professional Education": 4,
    "Complete professional education": 4,
    "Postgraduate education": 4
}
the_map={
    "Ninguno": 0,
    "Incomplete primary": 0,
    "Complete primary": 0,
    "Incomplete Secundary": 0,
    "Complete Secundary": 0,
    "Incomplete technical or technological": 1,
    "Complete technique or technology": 2,
    "Incomplete Professional Education": 0,
    "Complete professional education": 0,
    "Postgraduate education": 0
}
phe_map={
    "Ninguno": 0,
    "Incomplete primary": 0,
    "Complete primary": 0,
    "Incomplete Secundary": 0,
    "Complete Secundary": 0,
    "Incomplete technical or technological": 0,
    "Complete technique or technology": 0,
    "Incomplete Professional Education": 1,
    "Complete professional education": 2,
    "Postgraduate education": 3
}

In [6]:
#create new column
df1['EDU_BC_PARENTS']=(df1['EDU_FATHER'].map(bed_map)+df1['EDU_MOTHER'].map(bed_map))
df1['EDU_TH_PARENTS']=(df1['EDU_FATHER'].map(the_map)+df1['EDU_MOTHER'].map(the_map))
df1['EDU_PH_PARENTS']=(df1['EDU_FATHER'].map(phe_map)+df1['EDU_MOTHER'].map(phe_map))

#check
df1[
    [
        "EDU_FATHER",
        "EDU_MOTHER",
        "EDU_BC_PARENTS",
        "EDU_TH_PARENTS",
        "EDU_PH_PARENTS"
    ]
].head(20)

,EDU_FATHER,EDU_MOTHER,EDU_BC_PARENTS,EDU_TH_PARENTS,EDU_PH_PARENTS
0,Incomplete Professional Education,Complete technique or technology,8,2,1
1,Complete Secundary,Complete professional education,8,0,2
4,Complete professional education,Complete professional education,8,0,4
5,Complete professional education,Complete professional education,8,0,4
6,Complete professional education,Complete professional education,8,0,4
7,Incomplete Secundary,Complete Secundary,7,0,0
8,Complete Secundary,Complete professional education,8,0,2
9,Incomplete technical or technological,Incomplete technical or technological,8,2,0
11,Complete technique or technology,Complete Secundary,8,2,0
13,Complete professional education,Complete professional education,8,0,4
14,Incomplete primary,Incomplete primary,2,0,0
16,Complete professional education,Complete professional education,8,0,4
17,Complete professional education,Complete professional education,8,0,4
18,Complete technique or technology,Complete Secundary,8,2,0
19,Complete professional education,Complete professional education,8,0,4
20,Complete professional education,Complete professional education,8,0,4
21,Incomplete primary,Incomplete Secundary,4,0,0
22,Complete primary,Incomplete primary,3,0,0
23,Incomplete primary,Incomplete primary,2,0,0
24,Complete professional education,Incomplete Professional Education,8,0,3

In [7]:
df1[['EDU_BC_PARENTS','EDU_TH_PARENTS','EDU_PH_PARENTS']].describe().T

                  count      mean       std  min  25%  50%  75%  max
EDU_BC_PARENTS  11491.0  7.194239  1.528393  0.0  7.0  8.0  8.0  8.0
EDU_TH_PARENTS  11491.0  0.514490  1.031039  0.0  0.0  0.0  0.0  4.0
EDU_PH_PARENTS  11491.0  1.652598  1.930002  0.0  0.0  0.0  3.0  6.0

In [8]:
df1["TOTAL_S11"] = df1[["MAT_S11", "CR_S11", "CC_S11", "BIO_S11", "ENG_S11"]].sum(axis=1)
df1["TOTAL_PRO"] = df1[["CR_PRO", "QR_PRO", "CC_PRO", "WC_PRO", "ENG_PRO"]].sum(axis=1)

In [9]:
#descriptive statistics of parental education
ds1 = df1.groupby("EDU_FATHER").agg(
    COUNT=("EDU_FATHER", "size"),
    MEAN_TOTAL_S11=("TOTAL_S11", "mean"),
    MEAN_TOTAL_PRO=("TOTAL_PRO", "mean")
).sort_values("COUNT", ascending=False)
display(ds1)

ds1 = df1.groupby("EDU_MOTHER").agg(
    COUNT=("EDU_MOTHER", "size"),
    MEAN_TOTAL_S11=("TOTAL_S11", "mean"),
    MEAN_TOTAL_PRO=("TOTAL_PRO", "mean")
).sort_values("COUNT", ascending=False)
display(ds1)

                                       COUNT  MEAN_TOTAL_S11  MEAN_TOTAL_PRO
EDU_FATHER
Complete professional education         2995      324.770618      340.456427
Complete Secundary                      2831      301.154009      303.591664
Complete technique or technology        1188      314.205387      327.112795
Incomplete Secundary                    1076      296.632900      294.852230
Postgraduate education                  1071      348.019608      377.178338
Complete primary                         815      292.954601      288.885890
Incomplete primary                       692      295.917630      290.410405
Incomplete Professional Education        425      321.684706      340.272941
Incomplete technical or technological    276      308.014493      319.329710
Ninguno                                  122      296.532787      298.311475

                                       COUNT  MEAN_TOTAL_S11  MEAN_TOTAL_PRO
EDU_MOTHER
Complete Secundary                      3020      300.421192      302.675497
Complete professional education         2985      327.519933      345.471692
Complete technique or technology        1463      313.310321      323.229665
Incomplete Secundary                    1028      294.448444      290.016537
Postgraduate education                   968      343.235537      372.042355
Complete primary                         687      292.756914      288.585153
Incomplete Professional Education        488      320.258197      338.030738
Incomplete primary                       485      293.686598      287.323711
Incomplete technical or technological    334      311.254491      319.083832
Ninguno                                   33      297.909091      269.696970

In [10]:
#descriptive statistics of parental education
def descriptive_profile(series):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)

    return pd.Series({
        "count": series.count(),
        "mean": series.mean(),
        "median": series.median(),
        "mode": series.mode().iloc[0],
        "min": series.min(),
        "max": series.max(),
        "range": series.max() - series.min(),
        "variance": series.var(),
        "std_dev": series.std(),
        "Q1": q1,
        "Q3": q3,
        "IQR": q3 - q1,
        "skewness": series.skew()
    })


# Father's education
father_profile = (
    df1.groupby("EDU_FATHER")[["TOTAL_S11", "TOTAL_PRO"]].apply(lambda x: x.apply(descriptive_profile).T)
)
display(father_profile.round(2))


# Mother's education
mother_profile = (
    df1.groupby("EDU_MOTHER")[["TOTAL_S11", "TOTAL_PRO"]].apply(lambda x: x.apply(descriptive_profile).T)
)

display(mother_profile.round(2))

                                                  count    mean  median  \
EDU_FATHER
Complete Secundary                    TOTAL_S11  2831.0  301.15   299.0
                                      TOTAL_PRO  2831.0  303.59   312.0
Complete primary                      TOTAL_S11   815.0  292.95   289.0
                                      TOTAL_PRO   815.0  288.89   293.0
Complete professional education       TOTAL_S11  2995.0  324.77   324.0
                                      TOTAL_PRO  2995.0  340.46   354.0
Complete technique or technology      TOTAL_S11  1188.0  314.21   311.0
                                      TOTAL_PRO  1188.0  327.11   336.0
Incomplete Professional Education     TOTAL_S11   425.0  321.68   319.0
                                      TOTAL_PRO   425.0  340.27   352.0
Incomplete Secundary                  TOTAL_S11  1076.0  296.63   293.5
                                      TOTAL_PRO  1076.0  294.85   302.0
Incomplete primary                    TOTAL_S11   692.0  295.92   292.0
                                      TOTAL_PRO   692.0  290.41   295.5
Incomplete technical or technological TOTAL_S11   276.0  308.01   309.0
                                      TOTAL_PRO   276.0  319.33   325.0
Ninguno                               TOTAL_S11   122.0  296.53   304.5
                                      TOTAL_PRO   122.0  298.31   314.5
Postgraduate education                TOTAL_S11  1071.0  348.02   350.0
                                      TOTAL_PRO  1071.0  377.18   393.0

                                                  mode    min    max  range  \
EDU_FATHER
Complete Secundary                    TOTAL_S11  273.0  189.0  468.0  279.0
                                      TOTAL_PRO  254.0   15.0  491.0  476.0
Complete primary                      TOTAL_S11  288.0  189.0  439.0  250.0
                                      TOTAL_PRO  304.0   26.0  491.0  465.0
Complete professional education       TOTAL_S11  317.0  194.0  460.0  266.0
                                      TOTAL_PRO  445.0   23.0  497.0  474.0
Complete technique or technology      TOTAL_S11  285.0  209.0  478.0  269.0
                                      TOTAL_PRO  361.0   25.0  491.0  466.0
Incomplete Professional Education     TOTAL_S11  315.0  216.0  448.0  232.0
                                      TOTAL_PRO  341.0   73.0  492.0  419.0
Incomplete Secundary                  TOTAL_S11  291.0  179.0  446.0  267.0
                                      TOTAL_PRO  262.0   21.0  487.0  466.0
Incomplete primary                    TOTAL_S11  291.0  189.0  459.0  270.0
                                      TOTAL_PRO  210.0   32.0  493.0  461.0
Incomplete technical or technological TOTAL_S11  321.0  212.0  422.0  210.0
                                      TOTAL_PRO  296.0   67.0  487.0  420.0
Ninguno                               TOTAL_S11  275.0  194.0  413.0  219.0
                                      TOTAL_PRO  397.0   28.0  486.0  458.0
Postgraduate education                TOTAL_S11  370.0  214.0  475.0  261.0
                                      TOTAL_PRO  431.0   76.0  500.0  424.0

                                                 variance  std_dev      Q1  \
EDU_FATHER
Complete Secundary                    TOTAL_S11   2021.26    44.96  269.00
                                      TOTAL_PRO   9435.44    97.14  234.00
Complete primary                      TOTAL_S11   1778.05    42.17  263.00
                                      TOTAL_PRO   9636.34    98.16  219.00
Complete professional education       TOTAL_S11   2320.09    48.17  290.00
                                      TOTAL_PRO   8817.25    93.90  276.00
Complete technique or technology      TOTAL_S11   2023.46    44.98  282.00
                                      TOTAL_PRO   8437.87    91.86  264.00
Incomplete Professional Education     TOTAL_S11   2053.13    45.31  288.00
                                      TOTAL_PRO   8022.24    89.57  285.00
Incomplete Secundary                  TOTAL_S11   1938.95    44.03  266.00
                                      TOTAL_PRO   9309.09    96.48  222.75
Incomplete primary                    TOTAL_S11   1953.00    44.19  264.00
                                      TOTAL_PRO   8926.25    94.48  222.75
Incomplete technical or technological TOTAL_S11   1860.87    43.14  274.75
                                      TOTAL_PRO   8997.55    94.86  254.00
Ninguno                               TOTAL_S11   1951.31    44.17  263.25
                                      TOTAL_PRO   9910.98    99.55  219.25
Postgraduate education                TOTAL_S11   2118.66    46.03  319.00
                                      TOTAL_PRO   6642.52    81.50  331.50

                                                     Q3     IQR  skewness
EDU_FATHER
Complete Secundary                    TOTAL_S11  330.00   61.00      0.35
                                      TOTAL_PRO  380.00  146.00     -0.31
Complete primary                      TOTAL_S11  322.00   59.00      0.31
                                      TOTAL_PRO  364.00  145.00     -0.18
Complete professional education       TOTAL_S11  360.00   70.00      0.06
                                      TOTAL_PRO  414.00  138.00     -0.58
Complete technique or technology      TOTAL_S11  345.00   63.00      0.31
                                      TOTAL_PRO  401.25  137.25     -0.40
Incomplete Professional Education     TOTAL_S11  354.00   66.00      0.16
                                      TOTAL_PRO  413.00  128.00     -0.69
Incomplete Secundary                  TOTAL_S11  326.00   60.00      0.28
                                      TOTAL_PRO  370.00  147.25     -0.22
Incomplete primary                    TOTAL_S11  325.00   61.00      0.36
                                      TOTAL_PRO  360.25  137.50     -0.18
Incomplete technical or technological TOTAL_S11  337.25   62.50      0.10
                                      TOTAL_PRO  396.50  142.50     -0.42
Ninguno                               TOTAL_S11  326.75   63.50     -0.04
                                      TOTAL_PRO  376.00  156.75     -0.40
Postgraduate education                TOTAL_S11  380.00   61.00     -0.17
                                      TOTAL_PRO  441.00  109.50     -0.91

                                                  count    mean  median  \
EDU_MOTHER
Complete Secundary                    TOTAL_S11  3020.0  300.42   298.0
                                      TOTAL_PRO  3020.0  302.68   310.0
Complete primary                      TOTAL_S11   687.0  292.76   288.0
                                      TOTAL_PRO   687.0  288.59   291.0
Complete professional education       TOTAL_S11  2985.0  327.52   326.0
                                      TOTAL_PRO  2985.0  345.47   360.0
Complete technique or technology      TOTAL_S11  1463.0  313.31   311.0
                                      TOTAL_PRO  1463.0  323.23   333.0
Incomplete Professional Education     TOTAL_S11   488.0  320.26   319.0
                                      TOTAL_PRO   488.0  338.03   349.0
Incomplete Secundary                  TOTAL_S11  1028.0  294.45   292.0
                                      TOTAL_PRO  1028.0  290.02   296.5
Incomplete primary                    TOTAL_S11   485.0  293.69   291.0
                                      TOTAL_PRO   485.0  287.32   293.0
Incomplete technical or technological TOTAL_S11   334.0  311.25   312.0
                                      TOTAL_PRO   334.0  319.08   333.5
Ninguno                               TOTAL_S11    33.0  297.91   294.0
                                      TOTAL_PRO    33.0  269.70   294.0
Postgraduate education                TOTAL_S11   968.0  343.24   346.5
                                      TOTAL_PRO   968.0  372.04   392.0

                                                  mode    min    max  range  \
EDU_MOTHER
Complete Secundary                    TOTAL_S11  276.0  179.0  439.0  260.0
                                      TOTAL_PRO  360.0   21.0  493.0  472.0
Complete primary                      TOTAL_S11  263.0  193.0  439.0  246.0
                                      TOTAL_PRO  247.0   32.0  488.0  456.0
Complete professional education       TOTAL_S11  323.0  194.0  478.0  284.0
                                      TOTAL_PRO  388.0   26.0  499.0  473.0
Complete technique or technology      TOTAL_S11  303.0  200.0  461.0  261.0
                                      TOTAL_PRO  333.0   66.0  498.0  432.0
Incomplete Professional Education     TOTAL_S11  283.0  208.0  448.0  240.0
                                      TOTAL_PRO  344.0   25.0  492.0  467.0
Incomplete Secundary                  TOTAL_S11  274.0  189.0  440.0  251.0
                                      TOTAL_PRO  234.0   15.0  482.0  467.0
Incomplete primary                    TOTAL_S11  291.0  186.0  459.0  273.0
                                      TOTAL_PRO  219.0   51.0  493.0  442.0
Incomplete technical or technological TOTAL_S11  322.0  212.0  422.0  210.0
                                      TOTAL_PRO  347.0   67.0  487.0  420.0
Ninguno                               TOTAL_S11  272.0  210.0  387.0  177.0
                                      TOTAL_PRO  341.0   28.0  478.0  450.0
Postgraduate education                TOTAL_S11  356.0  206.0  475.0  269.0
                                      TOTAL_PRO  440.0   85.0  500.0  415.0

                                                 variance  std_dev      Q1  \
EDU_MOTHER
Complete Secundary                    TOTAL_S11   1922.76    43.85  269.00
                                      TOTAL_PRO   9234.65    96.10  234.00
Complete primary                      TOTAL_S11   1865.33    43.19  262.50
                                      TOTAL_PRO   9508.37    97.51  216.50
Complete professional education       TOTAL_S11   2386.65    48.85  291.00
                                      TOTAL_PRO   8683.61    93.19  282.00
Complete technique or technology      TOTAL_S11   2206.50    46.97  278.00
                                      TOTAL_PRO   8656.59    93.04  255.50
Incomplete Professional Education     TOTAL_S11   2113.46    45.97  289.75
                                      TOTAL_PRO   8016.21    89.53  283.75
Incomplete Secundary                  TOTAL_S11   1767.75    42.04  264.00
                                      TOTAL_PRO   9463.63    97.28  220.00
Incomplete primary                    TOTAL_S11   1923.41    43.86  264.00
                                      TOTAL_PRO   9386.27    96.88  219.00
Incomplete technical or technological TOTAL_S11   1898.94    43.58  277.25
                                      TOTAL_PRO   8120.75    90.12  253.25
Ninguno                               TOTAL_S11   2240.71    47.34  272.00
                                      TOTAL_PRO  12205.47   110.48  186.00
Postgraduate education                TOTAL_S11   2169.02    46.57  314.00
                                      TOTAL_PRO   7373.27    85.87  322.00

                                                     Q3     IQR  skewness
EDU_MOTHER
Complete Secundary                    TOTAL_S11  329.00   60.00      0.32
                                      TOTAL_PRO  377.00  143.00     -0.31
Complete primary                      TOTAL_S11  324.00   61.50      0.33
                                      TOTAL_PRO  364.00  147.50     -0.15
Complete professional education       TOTAL_S11  363.00   72.00      0.08
                                      TOTAL_PRO  419.00  137.00     -0.61
Complete technique or technology      TOTAL_S11  346.00   68.00      0.20
                                      TOTAL_PRO  397.00  141.50     -0.38
Incomplete Professional Education     TOTAL_S11  350.25   60.50      0.20
                                      TOTAL_PRO  406.25  122.50     -0.58
Incomplete Secundary                  TOTAL_S11  323.00   59.00      0.22
                                      TOTAL_PRO  365.25  145.25     -0.24
Incomplete primary                    TOTAL_S11  321.00   57.00      0.27
                                      TOTAL_PRO  361.00  142.00     -0.19
Incomplete technical or technological TOTAL_S11  339.75   62.50      0.19
                                      TOTAL_PRO  385.00  131.75     -0.46
Ninguno                               TOTAL_S11  327.00   55.00     -0.19
                                      TOTAL_PRO  341.00  155.00     -0.49
Postgraduate education                TOTAL_S11  377.00   63.00     -0.18
                                      TOTAL_PRO  438.25  116.25     -0.92

In [11]:
#statistical analysis
import statsmodels.formula.api as stat
#s11
mod_s11 = stat.ols("TOTAL_S11 ~ EDU_BC_PARENTS + EDU_TH_PARENTS + EDU_PH_PARENTS", data=df1).fit()
print(mod_s11.summary())
#pro
mod_pro = stat.ols("TOTAL_PRO ~ EDU_BC_PARENTS + EDU_TH_PARENTS + EDU_PH_PARENTS", data=df1).fit()
print(mod_pro.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_S11   R-squared:                       0.132
Model:                            OLS   Adj. R-squared:                  0.132
Method:                 Least Squares   F-statistic:                     581.3
Date:                Wed, 30 Sep 2026   Prob (F-statistic):               0.00
Time:                        06:18:22   Log-Likelihood:                -60058.
No. Observations:               11491   AIC:                         1.201e+05
Df Residuals:                   11487   BIC:                         1.202e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        288.6823      2.128    135.685      0.000     284.512     292.853
EDU_BC_PARENTS     0.9291      0.323      2.875      0.004       0.296       1.563
EDU_TH_PARENTS     4.4589      0.453      9.838      0.000       3.570       5.347
EDU_PH_PARENTS     9.0289      0.259     34.871      0.000       8.521       9.536
==============================================================================
Omnibus:                       87.798   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               81.776
Skew:                           0.172   Prob(JB):                     1.75e-18
Kurtosis:                       2.771   Cond. No.                         39.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_PRO   R-squared:                       0.086
Model:                            OLS   Adj. R-squared:                  0.085
Method:                 Least Squares   F-statistic:                     359.0
Date:                Wed, 30 Sep 2026   Prob (F-statistic):          7.36e-223
Time:                        06:18:22   Log-Likelihood:                -68414.
No. Observations:               11491   AIC:                         1.368e+05
Df Residuals:                   11487   BIC:                         1.369e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        276.3506      4.403     62.769      0.000     267.721     284.981
EDU_BC_PARENTS     2.4705      0.669      3.694      0.000       1.160       3.782
EDU_TH_PARENTS     7.5371      0.938      8.036      0.000       5.699       9.376
EDU_PH_PARENTS    14.2272      0.536     26.553      0.000      13.177      15.277
==============================================================================
Omnibus:                      449.455   Durbin-Watson:                   1.860
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              420.745
Skew:                          -0.419   Prob(JB):                     4.33e-92
Kurtosis:                       2.578   Cond. No.                         39.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [12]:
mod_math = stat.ols("MAT_S11 ~ EDU_BC_PARENTS + EDU_TH_PARENTS + EDU_PH_PARENTS",data=df1).fit()
mod_bio = stat.ols("BIO_S11 ~ EDU_BC_PARENTS + EDU_TH_PARENTS + EDU_PH_PARENTS",data=df1).fit()
mod_qr = stat.ols("QR_PRO ~ EDU_BC_PARENTS + EDU_TH_PARENTS + EDU_PH_PARENTS",data=df1).fit()
print(mod_math.summary())
print(mod_bio.summary())
print(mod_qr.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                MAT_S11   R-squared:                       0.089
Model:                            OLS   Adj. R-squared:                  0.089
Method:                 Least Squares   F-statistic:                     375.2
Date:                Wed, 30 Sep 2026   Prob (F-statistic):          1.63e-232
Time:                        06:18:22   Log-Likelihood:                -44234.
No. Observations:               11491   AIC:                         8.848e+04
Df Residuals:                   11487   BIC:                         8.851e+04
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         59.8575      0.537    111.497      0.000      58.805      60.910
EDU_BC_PARENTS     0.1725      0.082      2.115      0.034       0.013       0.332
EDU_TH_PARENTS     0.8694      0.114      7.602      0.000       0.645       1.094
EDU_PH_PARENTS     1.8377      0.065     28.128      0.000       1.710       1.966
==============================================================================
Omnibus:                      246.681   Durbin-Watson:                   1.803
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              262.879
Skew:                           0.360   Prob(JB):                     8.25e-58
Kurtosis:                       3.173   Cond. No.                         39.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                BIO_S11   R-squared:                       0.075
Model:                            OLS   Adj. R-squared:                  0.075
Method:                 Least Squares   F-statistic:                     309.4
Date:                Wed, 30 Sep 2026   Prob (F-statistic):          3.30e-193
Time:                        06:18:22   Log-Likelihood:                -43579.
No. Observations:               11491   AIC:                         8.717e+04
Df Residuals:                   11487   BIC:                         8.720e+04
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         60.6416      0.507    119.583      0.000      59.648      61.636
EDU_BC_PARENTS     0.0602      0.077      0.782      0.434      -0.091       0.211
EDU_TH_PARENTS     0.7764      0.108      7.187      0.000       0.565       0.988
EDU_PH_PARENTS     1.6136      0.062     26.147      0.000       1.493       1.735
==============================================================================
Omnibus:                      206.336   Durbin-Watson:                   1.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              227.087
Skew:                           0.300   Prob(JB):                     4.88e-50
Kurtosis:                       3.337   Cond. No.                         39.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                 QR_PRO   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     144.9
Date:                Wed, 30 Sep 2026   Prob (F-statistic):           3.59e-92
Time:                        06:18:22   Log-Likelihood:                -51959.
No. Observations:               11491   AIC:                         1.039e+05
Df Residuals:                   11487   BIC:                         1.040e+05
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         71.0792      1.052     67.597      0.000      69.018      73.140
EDU_BC_PARENTS     0.3287      0.160      2.058      0.040       0.016       0.642
EDU_TH_PARENTS     1.0844      0.224      4.841      0.000       0.645       1.523
EDU_PH_PARENTS     2.1824      0.128     17.054      0.000       1.932       2.433
==============================================================================
Omnibus:                     1846.276   Durbin-Watson:                   1.944
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2859.762
Skew:                          -1.167   Prob(JB):                         0.00
Kurtosis:                       3.727   Cond. No.                         39.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Which groups/stratum performs best? Are there differences between groups/stratums? Explain your analysis.

In [13]:
ap['STRATUM'].unique()

array(['Stratum 4', 'Stratum 5', 'Stratum 2', 'Stratum 6', 'Stratum 3',
       'Stratum 1', 0], dtype=object)

In [14]:
df2 = ap[~ap["STRATUM"].isin([0, "0"])].copy()

In [15]:
df2["TOTAL_S11"] = df2[["MAT_S11", "CR_S11", "CC_S11", "BIO_S11", "ENG_S11"]].sum(axis=1)
df2["TOTAL_PRO"] = df2[["CR_PRO", "QR_PRO", "CC_PRO", "WC_PRO", "ENG_PRO"]].sum(axis=1)

df2.groupby("STRATUM")[["TOTAL_S11", "TOTAL_PRO"]].mean()

            TOTAL_S11   TOTAL_PRO
STRATUM
Stratum 1  287.850790  275.221182
Stratum 2  299.725490  301.492182
Stratum 3  313.455624  326.014586
Stratum 4  334.267427  359.142586
Stratum 5  350.548183  378.342812
Stratum 6  362.394541  391.240695

In [16]:
#descriptive statistics of Stratum
stratum_profile = (
    df2.groupby("STRATUM")[["TOTAL_S11", "TOTAL_PRO"]]
       .apply(lambda x: x.apply(descriptive_profile).T)
)

display(stratum_profile.round(2))

                      count    mean  median   mode    min    max  range  \
STRATUM
Stratum 1 TOTAL_S11  1709.0  287.85   284.0  264.0  189.0  436.0  247.0
          TOTAL_PRO  1709.0  275.22   275.0  342.0   26.0  488.0  462.0
Stratum 2 TOTAL_S11  4029.0  299.73   297.0  290.0  179.0  469.0  290.0
          TOTAL_PRO  4029.0  301.49   309.0  329.0   15.0  500.0  485.0
Stratum 3 TOTAL_S11  4045.0  313.46   311.0  308.0  183.0  475.0  292.0
          TOTAL_PRO  4045.0  326.01   334.0  361.0   25.0  498.0  473.0
Stratum 4 TOTAL_S11  1578.0  334.27   334.0  334.0  199.0  478.0  279.0
          TOTAL_PRO  1578.0  359.14   374.5  437.0   43.0  499.0  456.0
Stratum 5 TOTAL_S11   633.0  350.55   352.0  379.0  226.0  460.0  234.0
          TOTAL_PRO   633.0  378.34   393.0  453.0   95.0  499.0  404.0
Stratum 6 TOTAL_S11   403.0  362.39   364.0  370.0  204.0  473.0  269.0
          TOTAL_PRO   403.0  391.24   413.0  453.0   96.0  499.0  403.0

                     variance  std_dev     Q1     Q3    IQR  skewness
STRATUM
Stratum 1 TOTAL_S11   1872.45    43.27  257.0  316.0   59.0      0.42
          TOTAL_PRO   9591.04    97.93  204.0  348.0  144.0     -0.08
Stratum 2 TOTAL_S11   1933.42    43.97  268.0  329.0   61.0      0.32
          TOTAL_PRO   9354.64    96.72  232.0  377.0  145.0     -0.25
Stratum 3 TOTAL_S11   2028.14    45.03  281.0  344.0   63.0      0.25
          TOTAL_PRO   8358.37    91.42  266.0  398.0  132.0     -0.45
Stratum 4 TOTAL_S11   2095.54    45.78  303.0  366.0   63.0     -0.02
          TOTAL_PRO   7294.71    85.41  306.0  428.0  122.0     -0.71
Stratum 5 TOTAL_S11   2008.78    44.82  321.0  381.0   60.0     -0.07
          TOTAL_PRO   6383.57    79.90  335.0  442.0  107.0     -0.85
Stratum 6 TOTAL_S11   1734.39    41.65  339.0  391.0   52.0     -0.37
          TOTAL_PRO   6417.58    80.11  352.0  451.0   99.0     -1.11

In [17]:
stn_map={
    "Stratum 1": 1,
    "Stratum 2": 2,
    "Stratum 3": 3,
    "Stratum 4": 4,
    "Stratum 5": 5,
    "Stratum 6": 6
}
#STN for STRATUM number
df2['STN']=df2['STRATUM'].map(stn_map)

In [18]:
import statsmodels.formula.api as stat

model_s11_stn = stat.ols("TOTAL_S11 ~ STN",data=df2).fit()
model_pro_stn = stat.ols("TOTAL_PRO ~ STN", data=df2).fit()

print(model_s11_stn.summary())
print(model_pro_stn.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_S11   R-squared:                       0.149
Model:                            OLS   Adj. R-squared:                  0.149
Method:                 Least Squares   F-statistic:                     2171.
Date:                Wed, 30 Sep 2026   Prob (F-statistic):               0.00
Time:                        06:18:22   Log-Likelihood:                -64636.
No. Observations:               12397   AIC:                         1.293e+05
Df Residuals:                   12395   BIC:                         1.293e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    269.0991      0.996    270.241      0.000     267.147     271.051
STN           15.5888      0.335     46.592      0.000      14.933      16.245
==============================================================================
Omnibus:                      115.435   Durbin-Watson:                   1.823
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              115.332
Skew:                           0.222   Prob(JB):                     9.04e-26
Kurtosis:                       2.836   Cond. No.                         8.13
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_PRO   R-squared:                       0.097
Model:                            OLS   Adj. R-squared:                  0.097
Method:                 Least Squares   F-statistic:                     1336.
Date:                Wed, 30 Sep 2026   Prob (F-statistic):          7.85e-278
Time:                        06:18:22   Log-Likelihood:                -73717.
No. Observations:               12397   AIC:                         1.474e+05
Df Residuals:                   12395   BIC:                         1.475e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    250.7027      2.071    121.026      0.000     246.642     254.763
STN           25.4378      0.696     36.548      0.000      24.073      26.802
==============================================================================
Omnibus:                      448.211   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              392.414
Skew:                          -0.373   Prob(JB):                     6.14e-86
Kurtosis:                       2.550   Cond. No.                         8.13
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

How does each gender perform in the global assessment?

In [19]:
ap['GENDER'].unique()

array(['F', 'M'], dtype=object)

In [20]:
df3=ap
df3["TOTAL_S11"] = df3[["MAT_S11", "CR_S11", "CC_S11", "BIO_S11", "ENG_S11"]].sum(axis=1)
df3["TOTAL_PRO"] = df3[["CR_PRO", "QR_PRO", "CC_PRO", "WC_PRO", "ENG_PRO"]].sum(axis=1)
df3.groupby("GENDER")[["TOTAL_S11", "TOTAL_PRO"]].mean()

         TOTAL_S11   TOTAL_PRO
GENDER
F       306.507039  314.955780
M       315.011672  323.461183

In [21]:
gender_profile = (
    df3.groupby("GENDER")[["TOTAL_S11", "TOTAL_PRO"]]
       .apply(lambda x: x.apply(descriptive_profile).T)
)

display(gender_profile.round(2))

                   count    mean  median   mode    min    max  range  \
GENDER
F      TOTAL_S11  5043.0  306.51   304.0  315.0  179.0  478.0  299.0
       TOTAL_PRO  5043.0  314.96   323.0  361.0   21.0  500.0  479.0
M      TOTAL_S11  7368.0  315.01   313.0  308.0  181.0  475.0  294.0
       TOTAL_PRO  7368.0  323.46   334.0  342.0   15.0  499.0  484.0

                  variance  std_dev     Q1     Q3    IQR  skewness
GENDER
F      TOTAL_S11   2111.75    45.95  273.0  338.0   65.0      0.26
       TOTAL_PRO   9485.84    97.40  245.0  395.0  150.0     -0.35
M      TOTAL_S11   2441.28    49.41  279.0  350.0   71.0      0.21
       TOTAL_PRO   9455.46    97.24  255.0  399.0  144.0     -0.43

In [22]:
#genn for gender number
genn_map={
    "F": 0,
    "M": 1
}
#STN for STRATUM number
df3['GENN']=df3['GENDER'].map(genn_map)

In [23]:
model_s11_gender = stat.ols("TOTAL_S11 ~ GENN",data=df3).fit()
model_pro_gender = stat.ols("TOTAL_PRO ~ GENN",data=df3).fit()

print(model_s11_gender.summary())
print(model_pro_gender.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_S11   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     93.85
Date:                Wed, 30 Sep 2026   Prob (F-statistic):           4.08e-22
Time:                        06:18:23   Log-Likelihood:                -65664.
No. Observations:               12411   AIC:                         1.313e+05
Df Residuals:                   12409   BIC:                         1.313e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    306.5070      0.676    453.132      0.000     305.181     307.833
GENN           8.5046      0.878      9.687      0.000       6.784      10.225
==============================================================================
Omnibus:                      185.735   Durbin-Watson:                   1.643
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              164.941
Skew:                           0.231   Prob(JB):                     1.53e-36
Kurtosis:                       2.676   Cond. No.                         2.90
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:              TOTAL_PRO   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     22.88
Date:                Wed, 30 Sep 2026   Prob (F-statistic):           1.75e-06
Time:                        06:18:23   Log-Likelihood:                -74425.
No. Observations:               12411   AIC:                         1.489e+05
Df Residuals:                   12409   BIC:                         1.489e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    314.9558      1.370    229.863      0.000     312.270     317.642
GENN           8.5054      1.778      4.783      0.000       5.020      11.991
==============================================================================
Omnibus:                      637.760   Durbin-Watson:                   1.752
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              492.161
Skew:                          -0.398   Prob(JB):                    1.34e-107
Kurtosis:                       2.437   Cond. No.                         2.90
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Use your analysis to understand the results.  What did you find interesting, and can you make any recommendations or inferences?